services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      APP_NAME: "Chat Guru"
      APP_URL: "http://localhost:5000"
      PORT: 5000
      MONGO_CONNECTION_STRING: "mongodb://mongo:27017/chat"
      COOKIE_SECRET: "iqbalsecret"
      JWT_SECRET: "test"
      JWT_EXPIRY: 86400000
      COOKIE_NAME: "iqbal-chat-app"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
